-- Fix programme names from jupas_programmes
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration' WHERE programme_code = 'JS6755';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Construction and Environment' WHERE programme_code = 'JS3004';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Intelligent Supply Chain and Engineering Management (Intelligent Supply Chain / Engineering Management with Data Analytics / Aviation Operations and Systems)' WHERE programme_code = 'JS3237';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education with Honours (Putonghua and Chinese Language Education) and Bachelor of Language Studies with Honours (Chinese Linguistic Studies)' WHERE programme_code = 'JS9520';
UPDATE jupas_scoring_formulas SET programme_name = 'Computing and Data Science (Delta+)' WHERE programme_code = 'JS6200';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in English Studies and Digital Communication and Bachelor of Education (Honours) (English Language)' WHERE programme_code = 'JS8004';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Bachelor of Education in Language Education - Chinese' WHERE programme_code = 'JS6080';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) in Civil Engineering' WHERE programme_code = 'JS3739';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Creative and Digital Arts (Visual Arts)' WHERE programme_code = 'JS8686';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Applied Psychology with Honours, Bachelor of Business Management with Honours' WHERE programme_code = 'JS9280';
UPDATE jupas_scoring_formulas SET programme_name = 'Interdisciplinary Major Programme in Global Economics and Finance' WHERE programme_code = 'JS4254';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Bachelor of Laws' WHERE programme_code = 'JS6078';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Surveying' WHERE programme_code = 'JS6016';
UPDATE jupas_scoring_formulas SET programme_name = 'Electronic Engineering' WHERE programme_code = 'JS4434';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Bachelor of Education in Language Education - English' WHERE programme_code = 'JS6066';
UPDATE jupas_scoring_formulas SET programme_name = 'B.Sc. in Learning Design and Technology' WHERE programme_code = 'JS4386';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Biotechnology and Chemical Technology' WHERE programme_code = 'JS3011';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Work' WHERE programme_code = 'JS6731';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering in Civil Engineering' WHERE programme_code = 'JS6353';
UPDATE jupas_scoring_formulas SET programme_name = 'Enrichment Stream in Theoretical Physics' WHERE programme_code = 'JS4690';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering in Computer Engineering / Electrical Engineering / Electronic Engineering' WHERE programme_code = 'JS6987';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Chinese Medicine' WHERE programme_code = 'JS6482';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Language Studies with Honours (Applied Chinese Language Studies)' WHERE programme_code = 'JS9550';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Sciences in Financial Technology' WHERE programme_code = 'JS6248';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Medicine and Bachelor of Surgery (Distinguished MedScholar)' WHERE programme_code = 'JS6626';
UPDATE jupas_scoring_formulas SET programme_name = 'Anthropology' WHERE programme_code = 'JS4006';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Sciences in Design+' WHERE programme_code = 'JS6236';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Speech-Language Pathology' WHERE programme_code = 'JS6157';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Nursing' WHERE programme_code = 'JS3648';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) Scheme in Product Innovation and Smart Manufacturing (Product Innovation with Marketing / Smart Manufacturing)' WHERE programme_code = 'JS3236';
UPDATE jupas_scoring_formulas SET programme_name = 'Professional Accountancy' WHERE programme_code = 'JS4240';
UPDATE jupas_scoring_formulas SET programme_name = 'Religious Studies' WHERE programme_code = 'JS4109';
UPDATE jupas_scoring_formulas SET programme_name = 'Translation' WHERE programme_code = 'JS4123';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Medicine and Bachelor of Surgery – Global Physician-Leadership Stream (MBChB-GPS)' WHERE programme_code = 'JS4502';
UPDATE jupas_scoring_formulas SET programme_name = 'Psychology' WHERE programme_code = 'JS4862';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts with Honours in English Language and Culture' WHERE programme_code = 'JS9019';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering with Honours in Electronic and Computer Engineering' WHERE programme_code = 'JS9720';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Nursing' WHERE programme_code = 'JS6468';
UPDATE jupas_scoring_formulas SET programme_name = 'Quantitative Finance' WHERE programme_code = 'JS4252';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration in Accounting and Finance / Bachelor of Business Administration in Accounting Data Analytics' WHERE programme_code = 'JS6781';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons)/BSc (Hons) Scheme in Information and Artificial Intelligence Engineering (Internet-of-Things / Artificial Intelligence / Information Security)' WHERE programme_code = 'JS3180';
UPDATE jupas_scoring_formulas SET programme_name = 'Fine Arts' WHERE programme_code = 'JS4044';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Architectural Studies' WHERE programme_code = 'JS3214';
UPDATE jupas_scoring_formulas SET programme_name = 'BA (Hons) Scheme in Applied Social Sciences (Social Work / Social Policy and Social Entrepreneurship)' WHERE programme_code = 'JS3250';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering in Mechanical Engineering' WHERE programme_code = 'JS6339';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Journalism, Media and Artificial Intelligence' WHERE programme_code = 'JS6822';
UPDATE jupas_scoring_formulas SET programme_name = 'Earth and Environmental Sciences' WHERE programme_code = 'JS4648';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Heritage Education and Arts Management' WHERE programme_code = 'JS8687';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Real Estate and Surveying' WHERE programme_code = 'JS9276';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Optometry' WHERE programme_code = 'JS3290';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Marketing' WHERE programme_code = 'JS9266';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Occupational Therapy' WHERE programme_code = 'JS3624';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Biomedical Engineering' WHERE programme_code = 'JS3150';
UPDATE jupas_scoring_formulas SET programme_name = 'Global Communication' WHERE programme_code = 'JS4858';
UPDATE jupas_scoring_formulas SET programme_name = 'Systems Engineering and Engineering Management' WHERE programme_code = 'JS4458';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science and Bachelor of Laws' WHERE programme_code = 'JS6858';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science' WHERE programme_code = 'JS6901';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science with Honours in Environmental Science and Green Management' WHERE programme_code = 'JS9731';
UPDATE jupas_scoring_formulas SET programme_name = 'Computational Data Science' WHERE programme_code = 'JS4416';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Integrated BBA Programme) and Juris Doctor Double Degree Programme' WHERE programme_code = 'JS4264';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Mental Health Nursing' WHERE programme_code = 'JS3337';
UPDATE jupas_scoring_formulas SET programme_name = 'BA (Hons) Scheme in Design (Advertising Design / Environmental Design / Information Design / Interaction Design / Interior Design / Media Design / Product Design / Service Design / Social Design)' WHERE programme_code = 'JS3569';
UPDATE jupas_scoring_formulas SET programme_name = 'Sociology' WHERE programme_code = 'JS4886';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Medicine and Bachelor of Surgery' WHERE programme_code = 'JS6456';
UPDATE jupas_scoring_formulas SET programme_name = 'Biomedical Sciences' WHERE programme_code = 'JS4550';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) Scheme in Mechanical Engineering (Intelligent Robotics Engineering / Mechanical Engineering)' WHERE programme_code = 'JS3741';
UPDATE jupas_scoring_formulas SET programme_name = 'Mathematics and Information Engineering' WHERE programme_code = 'JS4733';
UPDATE jupas_scoring_formulas SET programme_name = 'B.A. (English Studies) and B.Ed. (English Language Education)' WHERE programme_code = 'JS4343';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Creative and Digital Arts (Music)' WHERE programme_code = 'JS8685';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Heritage Education and Arts Management and Bachelor of Education (Honours) (Chinese History)' WHERE programme_code = 'JS8005';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education with Honours (Chinese Language Teaching) and Bachelor of Language Studies with Honours (Applied Chinese Language Studies)' WHERE programme_code = 'JS9560';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Humanities' WHERE programme_code = 'JS3007';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Surveying' WHERE programme_code = 'JS3789';
UPDATE jupas_scoring_formulas SET programme_name = 'Public Humanities' WHERE programme_code = 'JS4100';
UPDATE jupas_scoring_formulas SET programme_name = 'BA (Hons) Scheme in Fashion (Fashion Design / Knitwear Design / Contour Fashion and Activewear / Fashion Business / Fashion Innovation and Technology)' WHERE programme_code = 'JS3050';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering in Biomedical Engineering' WHERE programme_code = 'JS6925';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Professional Accounting' WHERE programme_code = 'JS9220';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Innovation and Technology' WHERE programme_code = 'JS6602';
UPDATE jupas_scoring_formulas SET programme_name = 'Materials Science and Engineering' WHERE programme_code = 'JS4470';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering and Master of Science in Engineering in Artificial Intelligence in Engineering' WHERE programme_code = 'JS6377';
UPDATE jupas_scoring_formulas SET programme_name = 'Science Master Class' WHERE programme_code = 'JS6688';
UPDATE jupas_scoring_formulas SET programme_name = 'Linguistics' WHERE programme_code = 'JS4070';
UPDATE jupas_scoring_formulas SET programme_name = 'Global Business Studies' WHERE programme_code = 'JS4214';
UPDATE jupas_scoring_formulas SET programme_name = 'Computer Science and Engineering' WHERE programme_code = 'JS4412';
UPDATE jupas_scoring_formulas SET programme_name = 'Artificial Intelligence: Systems and Technologies' WHERE programme_code = 'JS4468';
UPDATE jupas_scoring_formulas SET programme_name = 'Science' WHERE programme_code = 'JS4601';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Hotel and Tourism Management (Hotel Management / Smart Tourism and Hospitality / Event and Experience Management)' WHERE programme_code = 'JS3310';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Business Administration' WHERE programme_code = 'JS3003';
UPDATE jupas_scoring_formulas SET programme_name = 'Data Science and Policy Studies' WHERE programme_code = 'JS4893';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts with Honours in Language Studies and Translation' WHERE programme_code = 'JS9013';
UPDATE jupas_scoring_formulas SET programme_name = 'Integrated Bachelor of Business Administration Programme' WHERE programme_code = 'JS4202';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Digital Chinese Culture and Communication and Bachelor of Education (Honours) (Chinese Language)' WHERE programme_code = 'JS8003';
UPDATE jupas_scoring_formulas SET programme_name = 'Theology' WHERE programme_code = 'JS4111';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Digital Chinese Culture and Communication' WHERE programme_code = 'JS8674';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education and Bachelor of Science' WHERE programme_code = 'JS6119';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Business Management' WHERE programme_code = 'JS9230';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences' WHERE programme_code = 'JS6717';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology and Bachelor of Education (Honours) (Primary Mathematics)' WHERE programme_code = 'JS8009';
UPDATE jupas_scoring_formulas SET programme_name = 'B.A. (Chinese Language Studies) and B.Ed. (Chinese Language Education)' WHERE programme_code = 'JS4331';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Sports Science and Coaching and Bachelor of Education (Honours) (Physical Education)' WHERE programme_code = 'JS8010';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering Elite Programme' WHERE programme_code = 'JS6303';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) in Sociology and Community Studies and Bachelor of Education (Honours) (Primary Humanities)' WHERE programme_code = 'JS8013';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Personal Finance' WHERE programme_code = 'JS8688';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts in Landscape Studies' WHERE programme_code = 'JS6028';
UPDATE jupas_scoring_formulas SET programme_name = 'Financial Technology' WHERE programme_code = 'JS4428';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Computing and AI (Computer Science / Enterprise Information Systems)' WHERE programme_code = 'JS3868';
UPDATE jupas_scoring_formulas SET programme_name = 'Public Health' WHERE programme_code = 'JS4537';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Applied Science with Honours in Robotics and Automation Engineering' WHERE programme_code = 'JS9775';
UPDATE jupas_scoring_formulas SET programme_name = 'Chinese Medicine' WHERE programme_code = 'JS4542';
UPDATE jupas_scoring_formulas SET programme_name = 'Computing and Data Science' WHERE programme_code = 'JS6999';
UPDATE jupas_scoring_formulas SET programme_name = 'Biotechnology, Entrepreneurship and Healthcare Management' WHERE programme_code = 'JS4725';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Law) and Bachelor of Laws' WHERE programme_code = 'JS6808';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Biomedical Sciences' WHERE programme_code = 'JS6949';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA (Hons) Scheme in Accounting and Finance (Accountancy / Accounting and Finance / Digital Finance and Investment)' WHERE programme_code = 'JS3060';
UPDATE jupas_scoring_formulas SET programme_name = 'Insurance, Financial and Actuarial Analysis' WHERE programme_code = 'JS4238';
UPDATE jupas_scoring_formulas SET programme_name = 'Aerospace Science and Earth Informatics & X Double Major Programme' WHERE programme_code = 'JS4750';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts with Honours in Chinese' WHERE programme_code = 'JS9011';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Engineering in Data and Systems Engineering' WHERE programme_code = 'JS6315';
UPDATE jupas_scoring_formulas SET programme_name = 'Chinese Studies' WHERE programme_code = 'JS4136';
UPDATE jupas_scoring_formulas SET programme_name = 'Chinese Language and Literature' WHERE programme_code = 'JS4018';
UPDATE jupas_scoring_formulas SET programme_name = 'Enrichment Mathematics' WHERE programme_code = 'JS4682';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) Scheme in Aviation Engineering (Aeronautical Engineering / Air Transport Engineering)' WHERE programme_code = 'JS3140';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Special Education' WHERE programme_code = 'JS8663';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Sustainable Tourism and Hospitality Management' WHERE programme_code = 'JS9291';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Personal Finance and Bachelor of Education (Honours) (Business, Accounting and Financial Studies)' WHERE programme_code = 'JS8007';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Actuarial Science' WHERE programme_code = 'JS6729';
UPDATE jupas_scoring_formulas SET programme_name = 'Urban Studies' WHERE programme_code = 'JS4838';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education with Honours in English Language Teaching and Bachelor of English Language Studies with Honours' WHERE programme_code = 'JS9530';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology' WHERE programme_code = 'JS8714';
UPDATE jupas_scoring_formulas SET programme_name = 'BA (Hons) in Chinese History and Culture' WHERE programme_code = 'JS3320';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Spatial Data Science and Smart Cities (Land Surveying and Geo-Informatics / Urban Informatics and Smart Cities)' WHERE programme_code = 'JS3130';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Integrated Environmental Management' WHERE programme_code = 'JS8702';
UPDATE jupas_scoring_formulas SET programme_name = 'Higher Diploma in Early Childhood Education' WHERE programme_code = 'JS8507';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Global Business' WHERE programme_code = 'JS9240';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts in Global Creative Industries' WHERE programme_code = 'JS6274';
UPDATE jupas_scoring_formulas SET programme_name = 'Japanese Studies' WHERE programme_code = 'JS4068';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science with Honours in Science (STEAM)' WHERE programme_code = 'JS9733';
UPDATE jupas_scoring_formulas SET programme_name = 'Mechanical and Automation Engineering' WHERE programme_code = 'JS4408';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Sciences in Applied Artificial Intelligence' WHERE programme_code = 'JS6224';
UPDATE jupas_scoring_formulas SET programme_name = 'Global Studies' WHERE programme_code = 'JS4892';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts in Humanities and Digital Technologies' WHERE programme_code = 'JS6286';
UPDATE jupas_scoring_formulas SET programme_name = 'History' WHERE programme_code = 'JS4056';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Quantitative Finance' WHERE programme_code = 'JS6884';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Radiography' WHERE programme_code = 'JS3612';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Physics with a Secondary Major in Artificial Intelligence & Data Analytics (AIDA) / Innovation and Entrepreneurship (IE)' WHERE programme_code = 'JS3030';
UPDATE jupas_scoring_formulas SET programme_name = 'Global Engineering and Business Programme' WHERE programme_code = 'JS6937';
UPDATE jupas_scoring_formulas SET programme_name = 'B.Ed. in Early Childhood Education' WHERE programme_code = 'JS4372';
UPDATE jupas_scoring_formulas SET programme_name = 'Hospitality and Real Estate' WHERE programme_code = 'JS4226';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Medicine and Bachelor of Surgery (MBChB)' WHERE programme_code = 'JS4501';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Artificial Intelligence and Educational Technology and Bachelor of Education (Honours) (Information and Communication Technology and Primary Science)' WHERE programme_code = 'JS8008';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Integrated Environmental Management and Bachelor of Education (Honours) (Science)' WHERE programme_code = 'JS8011';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Building Engineering and Management' WHERE programme_code = 'JS3791';
UPDATE jupas_scoring_formulas SET programme_name = 'Human Movement Science and Health Studies' WHERE programme_code = 'JS4320';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Applied Mathematics and Finance Analytics (Applied Mathematics / Investment Science and Finance Analytics / Quantitative Finance and FinTech)' WHERE programme_code = 'JS3220';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science in Marketing Analytics and Technology' WHERE programme_code = 'JS6846';
UPDATE jupas_scoring_formulas SET programme_name = 'Economics' WHERE programme_code = 'JS4824';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) in Psychology and Bachelor of Education (Honours) (Early Childhood Education)' WHERE programme_code = 'JS8006';
UPDATE jupas_scoring_formulas SET programme_name = 'Physical Education, Exercise Science and Health' WHERE programme_code = 'JS4329';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Sports Science and Technology' WHERE programme_code = 'JS3160';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Economics / Bachelor of Economics and Finance' WHERE programme_code = 'JS6767';
UPDATE jupas_scoring_formulas SET programme_name = 'English' WHERE programme_code = 'JS4032';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts with Honours in Creative Advertising and Media Design' WHERE programme_code = 'JS9016';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science with Honours in Cyber and Computer Security' WHERE programme_code = 'JS9719';
UPDATE jupas_scoring_formulas SET programme_name = 'Geography and Resource Management' WHERE programme_code = 'JS4836';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Interdisciplinary Studies' WHERE programme_code = 'JS3000';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences with Honours in Psychology' WHERE programme_code = 'JS9010';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education with Honours in Early Childhood Education (Leadership and Special Educational Needs)' WHERE programme_code = 'JS9580';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Laws' WHERE programme_code = 'JS4903';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Language Science and Technology (Subject to approval)' WHERE programme_code = 'JS3243';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Creative and Digital Arts and Bachelor of Education (Honours) (Music)' WHERE programme_code = 'JS8001';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Psychology' WHERE programme_code = 'JS6705';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Sports Science and Coaching' WHERE programme_code = 'JS8726';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of English Language Studies with Honours' WHERE programme_code = 'JS9540';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Bachelor of Engineering in Artificial Intelligence and Data Science' WHERE programme_code = 'JS6298';
UPDATE jupas_scoring_formulas SET programme_name = 'Diplomacy and International Studies' WHERE programme_code = 'JS4898';
UPDATE jupas_scoring_formulas SET programme_name = 'Government and Public Administration' WHERE programme_code = 'JS4848';
UPDATE jupas_scoring_formulas SET programme_name = 'Nursing' WHERE programme_code = 'JS4513';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Creative and Digital Arts and Bachelor of Education (Honours) (Visual Arts)' WHERE programme_code = 'JS8002';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts' WHERE programme_code = 'JS6054';
UPDATE jupas_scoring_formulas SET programme_name = 'Information Engineering' WHERE programme_code = 'JS4446';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) in Sociology and Community Studies and Bachelor of Education (Honours) (Geography)' WHERE programme_code = 'JS8012';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in English Studies and Digital Communication' WHERE programme_code = 'JS8675';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science with Honours in Building Engineering and Management' WHERE programme_code = 'JS9776';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Sciences in Global Health and Development' WHERE programme_code = 'JS6250';
UPDATE jupas_scoring_formulas SET programme_name = 'Pharmacy' WHERE programme_code = 'JS4525';
UPDATE jupas_scoring_formulas SET programme_name = 'Music' WHERE programme_code = 'JS4082';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Business Analytics)' WHERE programme_code = 'JS6793';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Science' WHERE programme_code = 'JS3008';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Finance in Asset Management and Private Banking' WHERE programme_code = 'JS6860';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Food Science and Nutrition (Food Safety and Technology / Human Nutrition and Health)' WHERE programme_code = 'JS3255';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Laws' WHERE programme_code = 'JS6406';
UPDATE jupas_scoring_formulas SET programme_name = 'Journalism and Communication' WHERE programme_code = 'JS4850';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Engineering' WHERE programme_code = 'JS3005';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Medical Laboratory Science' WHERE programme_code = 'JS3478';
UPDATE jupas_scoring_formulas SET programme_name = 'Quantitative Finance and Risk Management Science' WHERE programme_code = 'JS4276';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor’s Degree Scheme in Computer and Mathematical Sciences' WHERE programme_code = 'JS3006';
UPDATE jupas_scoring_formulas SET programme_name = 'Interdisciplinary Data Analytics & X Double Major Programme' WHERE programme_code = 'JS4760';
UPDATE jupas_scoring_formulas SET programme_name = 'Philosophy' WHERE programme_code = 'JS4094';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Speech Therapy' WHERE programme_code = 'JS3242';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Government and Laws) and Bachelor of Laws' WHERE programme_code = 'JS6810';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Pharmacy' WHERE programme_code = 'JS6494';
UPDATE jupas_scoring_formulas SET programme_name = 'Social Work' WHERE programme_code = 'JS4874';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) Scheme in Data Science and Artificial Intelligence (Data Science and Analytics / Financial Technology and Artificial Intelligence)' WHERE programme_code = 'JS3223';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Education in Early Childhood Education and Special Education' WHERE programme_code = 'JS6092';
UPDATE jupas_scoring_formulas SET programme_name = 'Biomedical Engineering' WHERE programme_code = 'JS4460';
UPDATE jupas_scoring_formulas SET programme_name = 'BA (Hons) in English and Applied Linguistics' WHERE programme_code = 'JS3240';
UPDATE jupas_scoring_formulas SET programme_name = 'B.Ed. in Mathematics and Mathematics Education' WHERE programme_code = 'JS4361';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Speech Pathology and Rehabilitation' WHERE programme_code = 'JS8727';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Sports and eSports Management' WHERE programme_code = 'JS9294';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science with Honours in Biomedical Sciences and Biotechnology' WHERE programme_code = 'JS9732';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA (Hons) Scheme in Management and Marketing (Management / Marketing)' WHERE programme_code = 'JS3080';
UPDATE jupas_scoring_formulas SET programme_name = 'Energy and Environmental Engineering' WHERE programme_code = 'JS4462';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Dental Surgery' WHERE programme_code = 'JS6107';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts in Urban Studies' WHERE programme_code = 'JS6042';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Nursing Advanced Leadership Track' WHERE programme_code = 'JS6418';
UPDATE jupas_scoring_formulas SET programme_name = 'Architectural Studies' WHERE programme_code = 'JS4812';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences with Honours' WHERE programme_code = 'JS9009';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration in International Business and Global Management' WHERE programme_code = 'JS6896';
UPDATE jupas_scoring_formulas SET programme_name = 'Statistical Decision Sciences' WHERE programme_code = 'JS6779';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) in Psychology' WHERE programme_code = 'JS8651';
UPDATE jupas_scoring_formulas SET programme_name = 'Social Science' WHERE programme_code = 'JS4801';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc (Hons) in Physiotherapy' WHERE programme_code = 'JS3636';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration with Honours in Human Resource Management' WHERE programme_code = 'JS9262';
UPDATE jupas_scoring_formulas SET programme_name = 'Risk Management Science' WHERE programme_code = 'JS4719';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) in Building Sciences and Engineering' WHERE programme_code = 'JS3211';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts in Architectural Studies' WHERE programme_code = 'JS6004';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) Scheme in Electrical Engineering (Electrical Engineering / Transportation Systems Engineering)' WHERE programme_code = 'JS3170';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Biological Sciences (Features: Bioinformatics, Biochemistry, Genetics, Cellular & Molecular Biology, Immunology / Research Rotation Projects for Hands-on Experience)' WHERE programme_code = 'JS1806';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) / Bachelor of Music (Hons) (Music / Creative Industries)' WHERE programme_code = 'JS2060';
UPDATE jupas_scoring_formulas SET programme_name = 'Intelligent Information Systems [Majors: BBA Global Business Systems Management / BBA Artificial Intelligence in Business]' WHERE programme_code = 'JS1017';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Finance' WHERE programme_code = 'JS5312';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Computer Science and BSc Computational Finance and Financial Technology(Double Degree;Features:Corporate Accounting & Economics/Computational Finance/Advanced Statistics/Financial Technologies)' WHERE programme_code = 'JS1221';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Mechanical and Aerospace Engineering' WHERE programme_code = 'JS5270';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Operations Management' WHERE programme_code = 'JS5317';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Electronic and Computer Engineering' WHERE programme_code = 'JS5250';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Pharmacy (Hons) in Chinese Medicine' WHERE programme_code = 'JS2420';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) (Chinese Language and Literature / Creative and Professional Writing / English Language and Literature / Humanities / Translation)' WHERE programme_code = 'JS2020';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) in Visual Arts' WHERE programme_code = 'JS2810';
UPDATE jupas_scoring_formulas SET programme_name = 'Electrical Engineering (Majors: BEng Computer and Data Engineering / BEng Electronic and Electrical Engineering / BEng Information Engineering / BEng Microelectronics Engineering)' WHERE programme_code = 'JS1205';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Artificial Intelligence in Business (Streams: Business Intelligence / Information Systems Auditing / Internet Services and Social Networks / Data Informatics)' WHERE programme_code = 'JS1019';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) - Government and International Affairs' WHERE programme_code = 'JS7302';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Management' WHERE programme_code = 'JS5315';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours)-Economics (Optional Concentration: Global Economics & Banking)' WHERE programme_code = 'JS7301';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Computing Mathematics (Streams: Enriched Mathematics / Financial Mathematics / Global Research Enrichment and Technopreneurship (GREAT))' WHERE programme_code = 'JS1206';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc International Relations and Global Affairs (Streams: Asian Studies / International Studies / Development Studies)' WHERE programme_code = 'JS1102';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Animation and Digital Arts (Concentrations: Digital Animation/Arts & Technology)' WHERE programme_code = 'JS7133';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Creative Media (Features: Combination of Creative Media and Computer Science Courses / Animation / Games / Installation / Interactivity)' WHERE programme_code = 'JS1043';
UPDATE jupas_scoring_formulas SET programme_name = 'International Sustainability Programme for Innovation, Research & Entrepreneurship(INSPIRE) (Majors: BEng Energy Science & Engineering/BEng Environmental Science & Engineering +Features: Global Focus)' WHERE programme_code = 'JS1050';
UPDATE jupas_scoring_formulas SET programme_name = 'Data Science (Majors: BSc Data Science / BSc Data and Systems Engineering)' WHERE programme_code = 'JS1071';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Global Business' WHERE programme_code = 'JS5313';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Mathematics and Economics' WHERE programme_code = 'JS5813';
UPDATE jupas_scoring_formulas SET programme_name = 'BA Creative Media (Features: Animation / Cinema & Photography / Critical Theory & Practices / Game & Playable Media / New Media Art / Sound Art)' WHERE programme_code = 'JS1042';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Liberal Arts (Hons) in Global Development and Sustainability (Concentrations: Policy & Institutions/Culture & Community/Business & Economy/Human-Environment Interactions)' WHERE programme_code = 'JS7123';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Cultural Studies (Optional Concentrations: Digital Culture & Media Practices/Cultural Commons, Social Innovation & Creativity)' WHERE programme_code = 'JS7606';
UPDATE jupas_scoring_formulas SET programme_name = 'AI, Computing and Transformation (ACT) (Features: Free Choice of Major / One-to-One Advisor / Elite Work Placement / Executive Mentor Scheme / Premium Overseas Exchange / Internship Exchange)' WHERE programme_code = 'JS1070';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng Environmental Science and Engineering and BBA Finance (Double Degree; Features: Environmental, Social & Governance (ESG) / Green Finance / Environmental Technology / Interdisciplinary Education)' WHERE programme_code = 'JS1052';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng Materials Science and Engineering (Features: HKIE Accredited / Industrial and Research Internships / Overseas Double-degrees / Knowledge Transfer / World-leading Research)' WHERE programme_code = 'JS1210';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in English Studies (Optional Concentrations: Literature/Linguistics)' WHERE programme_code = 'JS7503';
UPDATE jupas_scoring_formulas SET programme_name = 'Energy and Environment (Majors: BEng Energy Science and Engineering / BEng Environmental Science and Engineering)' WHERE programme_code = 'JS1051';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Biotechnology and Business' WHERE programme_code = 'JS5811';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Chinese (Features: Chinese Language & Literature/Creative Writing/Digital Literature)' WHERE programme_code = 'JS7101';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Communication (Hons) in Game Design and Animation' WHERE programme_code = 'JS2370';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Marketing (Streams: Global Marketing / Marketing Analytics)' WHERE programme_code = 'JS1007';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in History (Optional Concentrations: Asian History/Global History)' WHERE programme_code = 'JS7709';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Marketing' WHERE programme_code = 'JS5316';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours)-Marketing and Social Media(Features: Integrated Marketing/Social Media & Digital Marketing/Consumer Behaviour & Marketing Research)' WHERE programme_code = 'JS7215';
UPDATE jupas_scoring_formulas SET programme_name = 'International Research Enrichment' WHERE programme_code = 'JS5101';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Environment and Sustainable Business (Features: Environmental Science / Business Sustainability / Environmental, Social & Governance (ESG))' WHERE programme_code = 'JS1053';
UPDATE jupas_scoring_formulas SET programme_name = 'Science (Group A)' WHERE programme_code = 'JS5102';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Information Systems' WHERE programme_code = 'JS5314';
UPDATE jupas_scoring_formulas SET programme_name = 'Global Research Enrichment and Technopreneurship (GREAT) [Majors: BSc Chemistry / BSc Computing Mathematics / BSc Physics + Global Research Enrichment and Technopreneurship (GREAT)]' WHERE programme_code = 'JS1200';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) in Film and Television' WHERE programme_code = 'JS2330';
UPDATE jupas_scoring_formulas SET programme_name = 'BA English (Streams: English and Professional Communication / Language and Literature)' WHERE programme_code = 'JS1104';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA (Hons) Scheme in Global Business and Logistics, Aviation, Maritime, and Supply Chain Management' WHERE programme_code = 'JS3070';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Innovation, Design and Technology' WHERE programme_code = 'JS5711';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Work (Hons)' WHERE programme_code = 'JS2660';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Risk Management and Business Intelligence' WHERE programme_code = 'JS5814';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng/BSc & BBA Dual Degree Program in Technology & Management' WHERE programme_code = 'JS5901';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Laws and BBA Accountancy (Double Degree)' WHERE programme_code = 'JS1062';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Philosophy (Features: Ethics/Philosophy of AI/Logic)' WHERE programme_code = 'JS7802';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Chemical and Biological Engineering' WHERE programme_code = 'JS5220';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc Crime Science (Features: Crime Prevention / Security Practice / Global Policing / Crime Analytics / Cyber and Future Crimes)' WHERE programme_code = 'JS1111';
UPDATE jupas_scoring_formulas SET programme_name = 'Architecture and Civil Engineering (Majors: BEng Architectural Engineering / BEng Civil Engineering / BSc Architecture and Surveying)' WHERE programme_code = 'JS1201';
UPDATE jupas_scoring_formulas SET programme_name = 'Business and Management' WHERE programme_code = 'JS5300';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Data Science (Features: Data Science / Machine Learning / Data Mining / Big Data Analysis)' WHERE programme_code = 'JS1072';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng Biomedical Engineering (Features: Medical Technology / Bioinstrumentation / Cell and Tissue Engineering / Biomedical Robotics)' WHERE programme_code = 'JS1211';
UPDATE jupas_scoring_formulas SET programme_name = 'Science (Group A) with Extended Major in Artificial Intelligence' WHERE programme_code = 'JS5181';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng in Computer Engineering' WHERE programme_code = 'JS5212';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) in Business Administration (Global Entertainment)' WHERE programme_code = 'JS2930';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Veterinary Medicine (Features: One Health / Animal Health & Welfare / Public Health / Dual Accreditation)' WHERE programme_code = 'JS1801';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours) in Risk and Insurance Management (Optional Concentration: Insurance Technology)(Features: Globally Recognised Qualifications/Exclusive Mentorship)' WHERE programme_code = 'JS7216';
UPDATE jupas_scoring_formulas SET programme_name = 'Pathway for Research, Innovation, and Multinational Engineering (PRIME) (any major in College of Engineering + Overseas Experience / Interdisciplinary / Entrepreneurial Training)' WHERE programme_code = 'JS1217';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Science (Hons) in Arts and Technology' WHERE programme_code = 'JS2920';
UPDATE jupas_scoring_formulas SET programme_name = 'BAS New Media (Features: Media Art / Robotics & AI / Art & Technology / Materials & Digital Fabrication)' WHERE programme_code = 'JS1044';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng Intelligent Manufacturing Engineering (Features: Industrial Internet-of-Things / Industrial Big Data / Robotics and Automation / Logistics and Supply Chain / Smart City Engineering)' WHERE programme_code = 'JS1216';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Hons)' WHERE programme_code = 'JS2510';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours)-Business Analytics & Innovation (Features: e-Business/Information Systems/Operations Management/Data Science/Artificial Intelligence)' WHERE programme_code = 'JS7212';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours)-Social and Public Policy Studies (Optional Concentration: Smart Cities & Digital Society)' WHERE programme_code = 'JS7306';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours)-Finance(Features:CFA Student Scholarship/Diverse Electives: Investment,Corporate Finance,FinTech)' WHERE programme_code = 'JS7213';
UPDATE jupas_scoring_formulas SET programme_name = 'BA Linguistics and Language Applications (Features: General Linguistics / Computational Linguistics / Corpus Linguistics / Experimental Linguistics / Language Technology and Applications)' WHERE programme_code = 'JS1109';
UPDATE jupas_scoring_formulas SET programme_name = 'Mechanical Engineering (Majors: BEng Aerospace Engineering / BEng Mechanical Engineering / BEng Nuclear and Risk Engineering)' WHERE programme_code = 'JS1207';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Biomedical Sciences (Features: Clinical Chemistry, Hematology, Microbiology and Pathology / Clinical or Industrial Attachment / Intensive Laboratory Experience)' WHERE programme_code = 'JS1807';
UPDATE jupas_scoring_formulas SET programme_name = 'Creative Media (Majors: BA Creative Media / BSc Creative Media / BAS New Media)' WHERE programme_code = 'JS1041';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Computer Science (Streams: Artificial Intelligence / Cybersecurity / Data Science / Multimedia Computing / Software Engineering and Project Management)' WHERE programme_code = 'JS1204';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Economics and Finance' WHERE programme_code = 'JS5331';
UPDATE jupas_scoring_formulas SET programme_name = 'Integrative Bioscience & Bioengineering Programme (Bio3) (Features: Free Choice of Major / Overseas Research Opportunities / Interdisciplinary)' WHERE programme_code = 'JS1300';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Accountancy (Streams: Professional Accounting / ESG and Tech)' WHERE programme_code = 'JS1002';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Sustainable and Green Finance' WHERE programme_code = 'JS5822';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Industrial Engineering and Decision Analytics' WHERE programme_code = 'JS5260';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Cybersecurity (Features: System Security / Software Security / Cryptography / Privacy-Enhancing Technologies / Cyber Risk Management)' WHERE programme_code = 'JS1218';
UPDATE jupas_scoring_formulas SET programme_name = 'BA Chinese and History (Streams: Chinese / History and Cultural Heritage)' WHERE programme_code = 'JS1103';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Civil and Environmental Engineering' WHERE programme_code = 'JS5230';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Hons) - Accounting Concentration' WHERE programme_code = 'JS2110';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Chemistry (Streams: Comprehensive Chemistry / Cosmetic Chemistry / Forensic Chemistry / Global Research Enrichment and Technopreneurship (GREAT))' WHERE programme_code = 'JS1202';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours) - Health and Social Services Management' WHERE programme_code = 'JS7305';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Hons)' WHERE programme_code = 'JS2120';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Professional Accounting' WHERE programme_code = 'JS5318';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) in Physical Education and Recreation Management' WHERE programme_code = 'JS2620';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng (Hons) in Environmental Engineering and Sustainable Development' WHERE programme_code = 'JS3375';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc Crime Science and Bachelor of Laws (Double Degree)' WHERE programme_code = 'JS1123';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Global Business (Features: 3 Exchanges/Joint Bachelor’s Degree Program with Columbia University (US)/Overseas Summer School & Study Tour/Business Consultancy Project/Scholarship and Sponsorship)' WHERE programme_code = 'JS1001';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) in Religion, Philosophy and Ethics' WHERE programme_code = 'JS2025';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Finance (Features: Investment Analysis / Financial Markets / Corporate Finance / Risk Management / Trading Room Workshop)' WHERE programme_code = 'JS1014';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Biomedical and Health Sciences' WHERE programme_code = 'JS5118';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours)-Social Data Science (Concentrations: Economics/Government and International Affairs/Psychology/Sociology)' WHERE programme_code = 'JS7307';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc Social Work (Features: Social Engagement and Concern for People’s Health and Well-Being / Human Diversities and Sustainability / People-in-Environment Interventions)' WHERE programme_code = 'JS1113';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours)-Sociology (Optional Concentration: Social Innovation & Social Studies)' WHERE programme_code = 'JS7304';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Data and Systems Engineering (Features: Data Science / FinTech & Decision Analytics / Industrial AI / Smart City)' WHERE programme_code = 'JS1074';
UPDATE jupas_scoring_formulas SET programme_name = 'BEng Innovation and Enterprise Engineering (Features: Engineering / Technology / Innovation / Enterprise / Entrepreneurship)' WHERE programme_code = 'JS1219';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours)-Management and Analytics (Concentration:Global Business Management & Analytics/Human Resource Management & Analytics)(Feature:Professional Membership)' WHERE programme_code = 'JS7214';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc Psychology (Streams: Health and Development / Mind and Brain)' WHERE programme_code = 'JS1112';
UPDATE jupas_scoring_formulas SET programme_name = 'Creative Arts and Technology Excellence (CREATE) (Options: Creative Media (School-based)/ BA Creative Media / BSc Creative Media / BAS New Media)' WHERE programme_code = 'JS1040';
UPDATE jupas_scoring_formulas SET programme_name = 'Economics and Finance (Majors: BBA Business Economics / BBA Finance)' WHERE programme_code = 'JS1012';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Laws' WHERE programme_code = 'JS1061';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Chinese Medicine and Bachelor of Science (Hons) in Biomedical Science' WHERE programme_code = 'JS2410';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA in Economics' WHERE programme_code = 'JS5311';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Quantitative Social Analysis' WHERE programme_code = 'JS5412';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Management (Streams: Human Resources Management / Strategy and International Management)' WHERE programme_code = 'JS1005';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Fine Arts (Hons) in Acting for Global Screen' WHERE programme_code = 'JS2340';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts, Science and Technology (Hons) in Individualised Major' WHERE programme_code = 'JS2950';
UPDATE jupas_scoring_formulas SET programme_name = 'Department of Computer Science and Engineering' WHERE programme_code = 'JS5240';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Physics [Features: Classical Physics/Modern Physics/Experimental and Computational Physics/Medical Physics/Condensed Matter Physics/Global Research Enrichment and Technopreneurship (GREAT)]' WHERE programme_code = 'JS1208';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Environmental Management and Technology' WHERE programme_code = 'JS5812';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Global Operations Management (Features: Supply Chain Management / Operations Efficiency / Process Improvement / Operations Analytics / Resource Planning)' WHERE programme_code = 'JS1027';
UPDATE jupas_scoring_formulas SET programme_name = 'Science (Group B)' WHERE programme_code = 'JS5103';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Hons) in Business Computing and Data Analytics' WHERE programme_code = 'JS2910';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc Computational Finance and Financial Technology (streams: Computational Finance / Financial Technology)' WHERE programme_code = 'JS1000';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Science (Honours) in Data Science (Features: Big Data Analytics/Deep Learning/Generative AI)' WHERE programme_code = 'JS7225';
UPDATE jupas_scoring_formulas SET programme_name = 'BSocSc Public Affairs and Management (Streams: Public Affairs and Governance / Public Policy and Management)' WHERE programme_code = 'JS1108';
UPDATE jupas_scoring_formulas SET programme_name = 'Media and Communication (Majors: BA Digital Television and Broadcasting / BA Media and Communication)' WHERE programme_code = 'JS1106';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Business Decision Analytics (Streams: Decision Analytics / Data Informatics)' WHERE programme_code = 'JS1026';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Global Business Systems Management (Features: Intelligent Technologies / Global Business / Study Exchange)' WHERE programme_code = 'JS1018';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Hons) / Bachelor of Social Sciences (Hons) (European Studies [French/German Stream] / Geography/ Global and China Studies/ Government and International Studies/ History/ Sociology)' WHERE programme_code = 'JS2610';
UPDATE jupas_scoring_formulas SET programme_name = 'Biomedical Sciences (Majors: BSc Biological Sciences / BSc Biomedical Sciences)' WHERE programme_code = 'JS1805';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Quantitative Finance' WHERE programme_code = 'JS5332';
UPDATE jupas_scoring_formulas SET programme_name = 'BSc in Global China Studies' WHERE programme_code = 'JS5411';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Communication (Hons) (Journalism and Digital Media / Public Relations and Advertising)' WHERE programme_code = 'JS2310';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts and Science (Hons) in Digital Futures and Humanities' WHERE programme_code = 'JS2960';
UPDATE jupas_scoring_formulas SET programme_name = 'Engineering with Extended Major in Artificial Intelligence' WHERE programme_code = 'JS5282';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Honours)-Psychology (Optional Concentrations: Counselling Psychology/Industrial & Organisational Psychology)' WHERE programme_code = 'JS7303';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Film and Visual Arts (Features: Film Studies/Global Media/Art History/Museum Studies)' WHERE programme_code = 'JS7905';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Arts (Honours) in Translation (Concentrations: Cross-cultural Communication/Digital Corporate Communication)' WHERE programme_code = 'JS7204';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Social Sciences (Hons) / Bachelor of Science (Hons) in Innovation in Health and Social Well-Being' WHERE programme_code = 'JS2940';
UPDATE jupas_scoring_formulas SET programme_name = 'Bachelor of Business Administration (Honours)-Accounting and Corporate Governance (Concentrations: Professional Accounting/Corporate Governance)(Features: Enhancement Programme/Industry Internship)' WHERE programme_code = 'JS7211';
UPDATE jupas_scoring_formulas SET programme_name = 'BBA Business Economics (Features: Economic Theory / International Economics / Economic and Business Forecasting / Quantitative Analysis)' WHERE programme_code = 'JS1013';
